version: "3.7"
services:
  app:
    build:
      args:
        user: abin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: playapp-image
    container_name: play-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - playapp

  db:
    image: mysql:5.7
    container_name: playapp-db
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ubuntu      
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - playapp

  nginx:
    image: nginx:alpine
    container_name: playapp-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - playapp

networks:
  playapp:
    driver: bridge
